coverage:
  if: true
  paths:
    - coverage.xml
codeToTestRatio:
  code:
    - 'src/**/*.php'
  test:
    - 'test/**/*Test.php'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
